### ISSUE TITLE
Удаляй нахуй репу

### ISSUE THREAD

**Issue by 1ffycat** [jezvgg/Stereometry-at-Python-PLT-#3]
![170800731-365a601c-f9b4-4635-90cd-8ce671ec70d3](https://github.com/jezvgg/Stereometry-at-Python-PLT-/assets/27009596/3527e27c-00eb-4d63-8276-2aa7c55168e0)

**Comment by axonde** [comment]
я согласен, это полный шлак

**Comment by alblak52yeei** [comment]
пиздец согласен автор еблан

**Comment by 1ffycat** [comment]
Все, вопросов нет, таску закрываю
