### ISSUE TITLE
Comments and method/class docstrings

### ISSUE THREAD

**Issue by 1ffycat** [jezvgg/Stereometry-at-Python-PLT-#7]
Репа без документации, не надо так

**Comment by 1ffycat** [comment]
Yes yes, London is the capital of Great Britain

**Comment by jezvgg** [comment]
А какую ты документацию хочешь? Все описано в Readme

**Comment by jezvgg** [comment]
![image](https://github.com/jezvgg/Stereometry-at-Python-PLT-/assets/40557881/867a13cb-83de-460e-a87a-39e8090ebc56)
Уже давно сделано, там где нужно. Но в будущем допишу.
